### ISSUE TITLE
Hacer ruta manual bienvenida usuarios

### ISSUE THREAD

**Issue by Juliantorresmendez** [lordmacu/meetwork#16]
hacer el envio mecánico de bienvenida a los usuarios q nos les llego por algún motivo el bienvenido meetwrok.co/sendHelloUser

**Comment by lordmacu** [comment]
esta es la ruta para volver a enviar la validacion de la cuenta al usuario, se tiene que tener en cuenta que primero hay que ver la base de datos y ver si ya esta creado o duplicado y borrar el que no es y despues tomar el id del que es y ponerlo al final de la ruta

dev-> http://dev.meetwork.co/sendHelloUser/242 
prod-> http://meetwork.co/sendHelloUser/242

**Comment by Juliantorresmendez** [comment]
-[x] dEv
-[ ] Prod

**Comment by Juliantorresmendez** [comment]
- [x] dEv
- [ ] Prod
